### ISSUE TITLE
Addition of a requirements file

### ISSUE THREAD

**Issue by ntwalibas** [LSaldyt/curry#11]
When a user clones the repository and attempts to run the examples, packages are missing; e.g. seaborn.
Can you please add a requirements.txt from which a virtual environment can be created? Without it, installation for prospective users will be an unpleasant experience.

**Comment by LSaldyt** [comment]
Thanks for the suggestion! Actually, when I look at it, `seaborn`, `matplotlib`, and `pandas` are just libraries I've used for plotting stuff while I hack on curry, but the only true requirements are `numpy` and `pyquil`. I've added two requirements files reflecting this in a recent commit. I'll write up some basic usage instructions in the README too, since I know the project is missing those and is probably hard to understand without them.

**Comment by ntwalibas** [comment]
Sounds good. Waiting for the update so I can give more feedback.
I felt just having the requirement file is enough since I can create a virtual environment and install everything into it using pip.

P.S.: I did send you the email, using nbashige at gmail. Did you get the same?

**Comment by LSaldyt** [comment]
It's been added! I got your email, but haven't had the time for a thorough reply. Expect to hear from me soon! I'll have much more time once school is over (Dec 6th)
